# --------------------------------------------------------------------------------
# Number of Weaviate Pods
# --------------------------------------------------------------------------------
replicaCount: 3

# --------------------------------------------------------------------------------
# Weaviate Docker Image
# --------------------------------------------------------------------------------
image:
  repository: semitechnologies/weaviate
  # For production, pin the version carefully, e.g.:
  tag: v1.20.0
  pullPolicy: IfNotPresent

# --------------------------------------------------------------------------------
# Persistence (PVC)
# --------------------------------------------------------------------------------
persistence:
  enabled: true
  size: 50Gi
  storageClass: gp3  # Must match the name in our StorageClass resource

# --------------------------------------------------------------------------------
# Environment Variables
# --------------------------------------------------------------------------------
env:
  - name: QUERY_DEFAULTS_LIMIT
    value: "25"
  - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
    value: "true"
  - name: PERSISTENCE_DATA_PATH
    value: "/var/lib/weaviate"

  # (Optional) S3 backups, if you configure IAM perms or credentials:
  - name: BACKUP_S3_BUCKET
    value: "my-weaviate-backups"
  - name: BACKUP_S3_ENDPOINT
    value: "s3.amazonaws.com"
  - name: BACKUP_S3_REGION
    value: "us-east-1"

# --------------------------------------------------------------------------------
# Liveness & Readiness Probes
# --------------------------------------------------------------------------------
livenessProbe:
  enabled: true
readinessProbe:
  enabled: true

# --------------------------------------------------------------------------------
# Service
# --------------------------------------------------------------------------------
service:
  type: ClusterIP
  port: 8080
  annotations: {}

# --------------------------------------------------------------------------------
# Ingress (Optional)
# --------------------------------------------------------------------------------
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: weaviate.my-domain.com
      paths:
        - /
  tls: []
